AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  LambdaCodeBucket:
    Type: String

  LambdaCodeKey:
    Type: String

Resources:

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: java-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  HelloLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: hello-java-lambda
      Runtime: java17
      Handler: com.example.lambda.HelloLambda::handleRequest
      Role: !GetAtt LambdaExecutionRole.Arn
      MemorySize: 512
      Timeout: 30

      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaCodeKey

Outputs:
  LambdaArn:
    Value: !GetAtt HelloLambda.Arn